version: '3.8'

services:
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: sentinel_fhir
    user: root
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:h2:file:/data/hapi/database;AUTO_SERVER=TRUE
      - hapi.fhir.tester.home.name=Sentinel Local FHIR
    volumes:
      - fhir_data:/data/hapi
    networks:
      - shared-db-net

  ollama:
    image: ollama/ollama
    container_name: sentinel-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - shared-db-net

  nginx:
    image: nginx:alpine
    container_name: sentinel-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - shared-db-net

  whisper-service:
    build: ./whisper-service
    container_name: sentinel_whisper
    networks:
      - shared-db-net
    volumes:
      - audio_data:/app/audio_data

  backend:
    build: ./backend
    container_name: sentinel_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - shared-db-net
    volumes:
      - audio_data:/app/audio_data

  ai-service:
    build: ./ai-service
    container_name: sentinel_ai
    env_file:
      - .env
    networks:
      - shared-db-net

  frontend:
    build: ./sentinel-core-health
    container_name: sentinel-core-health
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - shared-db-net
    volumes:
      - ./sentinel-core-health:/app
      - /app/node_modules

volumes:
  fhir_data:
  ollama_data:
  audio_data:

networks:
  shared-db-net:
    external: true
    name: shared-db-net
